# Generated by Django 5.1.7 on 2025-03-21 03:09

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[users.models.validate_fmis_email],
            ),
        ),
    ]
