# Generated by Django 5.1.7 on 2025-03-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "Regular User"),
                    ("ADMIN", "Administrator"),
                    ("SUPERUSER", "Super User"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
    ]
