# Generated by Django 5.1.7 on 2025-03-24 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_phone_number_user_is_suspended_and_more"),
        ("users", "0007_alter_user_role"),
    ]

    operations = []
