# Generated by Django 5.1.7 on 2025-03-24 01:56

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_merge_20250322_1408"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_suspended",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login_attempt",
        ),
        migrations.RemoveField(
            model_name="user",
            name="login_attempts",
        ),
        migrations.RemoveField(
            model_name="user",
            name="suspended_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="suspension_reason",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[users.models.validate_fmis_email],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "Regular User"),
                    ("ADMIN", "Administrator"),
                    ("SUPERUSER", "Super User"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
    ]
