# Generated by Django 5.1.7 on 2025-03-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_mobiledevice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mobiledevice",
            name="app_version",
        ),
        migrations.RemoveField(
            model_name="mobiledevice",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="mobiledevice",
            name="device_model",
        ),
        migrations.RemoveField(
            model_name="mobiledevice",
            name="device_os",
        ),
        migrations.RemoveField(
            model_name="mobiledevice",
            name="last_login",
        ),
        migrations.AddField(
            model_name="mobiledevice",
            name="last_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobiledevice",
            name="token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
