# Generated by Django 5.1.7 on 2025-03-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_mobiledevice_app_version_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobiledevice",
            old_name="last_token",
            new_name="access_token",
        ),
        migrations.AddField(
            model_name="mobiledevice",
            name="last_login",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="mobiledevice",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
