# Generated by Django 5.1.7 on 2025-03-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_rename_last_token_mobiledevice_access_token_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobiledevice",
            old_name="access_token",
            new_name="last_token",
        ),
        migrations.RemoveField(
            model_name="mobiledevice",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="mobiledevice",
            name="refresh_token",
        ),
    ]
