# Generated by Django 5.1.7 on 2025-03-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_rename_access_token_mobiledevice_last_token_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobiledevice",
            old_name="last_token",
            new_name="access_token",
        ),
        migrations.AddField(
            model_name="mobiledevice",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
