# Generated by Django 5.1.7 on 2025-04-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_rename_last_token_mobiledevice_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobiledevice",
            name="device_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobiledevice",
            name="device_type",
            field=models.TextField(blank=True, null=True),
        ),
    ]
