# Generated by Django 5.1.7 on 2025-04-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_mobiledevice_device_name_mobiledevice_device_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        )
    ]
