# Generated by Django 5.1.7 on 2025-04-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_usercomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MALE", "Male"),
                    ("FEMALE", "Female"),
                    ("OTHER", "Other"),
                    ("PREFER_NOT_TO_SAY", "Prefer Not to Say"),
                ],
                max_length=20,
                null=True,
                verbose_name="Sex",
            ),
        ),
    ]
