# Generated by Django 5.1.7 on 2025-04-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_user_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
