# Generated by Django 5.1.7 on 2025-03-28 07:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word_kh",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Khmer Word"
                    ),
                ),
                (
                    "word_kh_type",
                    models.CharField(
                        choices=[
                            ("noun", "Noun"),
                            ("verb", "Verb"),
                            ("adjective", "Adjective"),
                            ("adverb", "Adverb"),
                            ("pronoun", "Pronoun"),
                            ("preposition", "Preposition"),
                            ("conjunction", "Conjunction"),
                            ("interjection", "Interjection"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "word_kh_definition",
                    models.TextField(
                        db_index=True, verbose_name="Khmer Word Definition"
                    ),
                ),
                (
                    "word_en",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="English Word"
                    ),
                ),
                (
                    "word_en_type",
                    models.CharField(
                        choices=[
                            ("noun", "Noun"),
                            ("verb", "Verb"),
                            ("adjective", "Adjective"),
                            ("adverb", "Adverb"),
                            ("pronoun", "Pronoun"),
                            ("preposition", "Preposition"),
                            ("conjunction", "Conjunction"),
                            ("interjection", "Interjection"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "word_en_definition",
                    models.TextField(
                        db_index=True, verbose_name="English Word Definition"
                    ),
                ),
                (
                    "example_sentence_kh",
                    models.TextField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Example Sentence in Khmer",
                    ),
                ),
                (
                    "example_sentence_en",
                    models.TextField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Example Sentence in English",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dictionary Entries",
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("access_count", models.PositiveIntegerField(default=0)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="dictionary.dictionary",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word_kh",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, "Khmer word cannot be empty"
                            )
                        ],
                        verbose_name="Khmer Word",
                    ),
                ),
                (
                    "word_en",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, "English word cannot be empty"
                            )
                        ],
                        verbose_name="English Word",
                    ),
                ),
                (
                    "word_kh_type",
                    models.CharField(
                        choices=[
                            ("នាម", "Noun"),
                            ("កិរិយាសព្ទ", "Verb"),
                            ("គុណនាម", "Adjective"),
                            ("គុណកិរិយា", "Adverb"),
                            ("សព្វនាម", "Pronoun"),
                            ("ធ្នាក់", "Preposition"),
                            ("ឈ្នាប់", "Conjunction"),
                            ("ឧទានសព្ទ", "Interjection"),
                        ],
                        max_length=50,
                        verbose_name="Khmer Word Type",
                    ),
                ),
                (
                    "word_en_type",
                    models.CharField(
                        choices=[
                            ("NOUN", "Noun"),
                            ("VERB", "Verb"),
                            ("ADJECTIVE", "Adjective"),
                            ("ADVERB", "Adverb"),
                            ("PRONOUN", "Pronoun"),
                            ("PREPOSITION", "Preposition"),
                            ("CONJUNCTION", "Conjunction"),
                            ("INTERJECTION", "Interjection"),
                        ],
                        max_length=20,
                        verbose_name="English Word Type",
                    ),
                ),
                (
                    "word_kh_definition",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                5, "Definition must be at least 5 characters"
                            )
                        ],
                        verbose_name="Khmer Word Definition",
                    ),
                ),
                (
                    "word_en_definition",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                5, "Definition must be at least 5 characters"
                            )
                        ],
                        verbose_name="English Word Definition",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pronunciation_kh",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Khmer Pronunciation",
                    ),
                ),
                (
                    "pronunciation_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="English Pronunciation",
                    ),
                ),
                (
                    "example_sentence_kh",
                    models.TextField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Example Sentence in Khmer",
                    ),
                ),
                (
                    "example_sentence_en",
                    models.TextField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Example Sentence in English",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staging_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_staging_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staging Dictionary Entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dictionary",
            index=models.Index(
                fields=["word_kh", "word_en"], name="dictionary__word_kh_48567a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dictionary",
            index=models.Index(
                fields=["word_kh_definition", "word_en_definition"],
                name="dictionary__word_kh_35baa7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dictionary",
            index=models.Index(
                fields=["example_sentence_kh", "example_sentence_en"],
                name="dictionary__example_1a6b75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["device_id", "created_at"],
                name="dictionary__device__588af4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["last_accessed"], name="dictionary__last_ac_faa94b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["access_count"], name="dictionary__access__9ddf1a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together={("device_id", "word")},
        ),
        migrations.AlterUniqueTogether(
            name="staging",
            unique_together={("word_kh", "word_en")},
        ),
    ]
