# Generated by Django 5.1.7 on 2025-03-19 07:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_kh", models.CharField(max_length=255)),
                ("word_en", models.CharField(max_length=255)),
                ("definition_kh", models.TextField()),
                ("definition_en", models.TextField()),
                (
                    "word_type_en",
                    models.CharField(
                        choices=[
                            ("NOUN", "Noun"),
                            ("VERB", "Verb"),
                            ("ADJECTIVE", "Adjective"),
                            ("ADVERB", "Adverb"),
                            ("PRONOUN", "Pronoun"),
                            ("PREPOSITION", "Preposition"),
                            ("CONJUNCTION", "Conjunction"),
                            ("INTERJECTION", "Interjection"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "word_type_kh",
                    models.CharField(
                        choices=[
                            ("នាម", "Noun"),
                            ("កិរិយាសព្ទ", "Verb"),
                            ("គុណនាម", "Adjective"),
                            ("គុណកិរិយា", "Adverb"),
                            ("សព្វនាម", "Pronoun"),
                            ("ធ្នាក់", "Preposition"),
                            ("ឈ្នាប់", "Conjunction"),
                            ("ឧទានសព្ទ", "Interjection"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_words",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_words",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dictionary Words",
                "ordering": ["-created_at"],
            },
        ),
    ]
