# Generated by Django 5.1.7 on 2025-03-26 02:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DictionaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word_kh",
                    models.CharField(max_length=255, verbose_name="Khmer Word"),
                ),
                (
                    "word_kh_type",
                    models.CharField(
                        choices=[
                            ("នាម", "Noun"),
                            ("កិរិយាសព្ទ", "Verb"),
                            ("គុណនាម", "Adjective"),
                            ("គុណកិរិយា", "Adverb"),
                            ("សព្វនាម", "Pronoun"),
                            ("ធ្នាក់", "Preposition"),
                            ("ឈ្នាប់", "Conjunction"),
                            ("ឧទានសព្ទ", "Interjection"),
                        ],
                        max_length=50,
                        verbose_name="Khmer Word Type",
                    ),
                ),
                (
                    "word_kh_definition",
                    models.TextField(verbose_name="Khmer Word Definition"),
                ),
                (
                    "word_en",
                    models.CharField(max_length=255, verbose_name="English Word"),
                ),
                (
                    "word_en_type",
                    models.CharField(
                        choices=[
                            ("NOUN", "Noun"),
                            ("VERB", "Verb"),
                            ("ADJECTIVE", "Adjective"),
                            ("ADVERB", "Adverb"),
                            ("PRONOUN", "Pronoun"),
                            ("PREPOSITION", "Preposition"),
                            ("CONJUNCTION", "Conjunction"),
                            ("INTERJECTION", "Interjection"),
                        ],
                        max_length=20,
                        verbose_name="English Word Type",
                    ),
                ),
                (
                    "word_en_definition",
                    models.TextField(verbose_name="English Word Definition"),
                ),
                (
                    "index",
                    models.IntegerField(unique=True, verbose_name="Dictionary Index"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "pronunciation_kh",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pronunciation_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("example_sentence_kh", models.TextField(blank=True, null=True)),
                ("example_sentence_en", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dictionary Entries",
                "ordering": ["index"],
                "unique_together": {("word_kh", "word_en")},
            },
        ),
        migrations.DeleteModel(
            name="Dictionary",
        ),
    ]
