# Generated by Django 5.1.7 on 2025-04-23 09:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="staging",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staging",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_staging_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="staging",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, "Rejection reason must be at least 10 characters long"
                    )
                ],
                verbose_name="Reason for Rejection",
            ),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_dictionary_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
