# Generated by Django 5.1.7 on 2025-04-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='staging',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staging',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='staging',
            index=models.Index(fields=['is_parent'], name='staging_is_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='staging',
            index=models.Index(fields=['is_child'], name='staging_is_child_idx'),
        )
    ]
