# Generated by Django 5.1.7 on 2025-03-26 03:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0002_dictionaryentry_delete_dictionary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StagingDictionaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word_kh",
                    models.CharField(max_length=255, verbose_name="Khmer Word"),
                ),
                (
                    "word_kh_type",
                    models.CharField(max_length=50, verbose_name="Khmer Word Type"),
                ),
                (
                    "word_kh_definition",
                    models.TextField(verbose_name="Khmer Word Definition"),
                ),
                (
                    "word_en",
                    models.CharField(max_length=255, verbose_name="English Word"),
                ),
                (
                    "word_en_type",
                    models.CharField(max_length=20, verbose_name="English Word Type"),
                ),
                (
                    "word_en_definition",
                    models.TextField(verbose_name="English Word Definition"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "pronunciation_kh",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pronunciation_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("example_sentence_kh", models.TextField(blank=True, null=True)),
                ("example_sentence_en", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staging_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_staging_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staging Dictionary Entries",
                "unique_together": {("word_kh", "word_en")},
            },
        ),
    ]
