# Generated by Django 5.1.7 on 2025-03-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0003_stagingdictionaryentry"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dictionaryentry",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="stagingdictionaryentry",
            name="word_en_type",
            field=models.CharField(
                choices=[
                    ("NOUN", "Noun"),
                    ("VERB", "Verb"),
                    ("ADJECTIVE", "Adjective"),
                    ("ADVERB", "Adverb"),
                    ("PRONOUN", "Pronoun"),
                    ("PREPOSITION", "Preposition"),
                    ("CONJUNCTION", "Conjunction"),
                    ("INTERJECTION", "Interjection"),
                ],
                max_length=20,
                verbose_name="English Word Type",
            ),
        ),
        migrations.AlterField(
            model_name="stagingdictionaryentry",
            name="word_kh_type",
            field=models.CharField(
                choices=[
                    ("នាម", "Noun"),
                    ("កិរិយាសព្ទ", "Verb"),
                    ("គុណនាម", "Adjective"),
                    ("គុណកិរិយា", "Adverb"),
                    ("សព្វនាម", "Pronoun"),
                    ("ធ្នាក់", "Preposition"),
                    ("ឈ្នាប់", "Conjunction"),
                    ("ឧទានសព្ទ", "Interjection"),
                ],
                max_length=50,
                verbose_name="Khmer Word Type",
            ),
        ),
        migrations.RemoveField(
            model_name="dictionaryentry",
            name="review_status",
        ),
        migrations.RemoveField(
            model_name="dictionaryentry",
            name="reviewed_at",
        ),
        migrations.RemoveField(
            model_name="dictionaryentry",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="dictionaryentry",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="dictionaryentry",
            name="updated_by",
        ),
    ]
