# Generated by Django 5.1.7 on 2025-03-26 04:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0004_alter_dictionaryentry_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stagingdictionaryentry",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Staging Dictionary Entries",
            },
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="difficulty_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BEGINNER", "Beginner"),
                    ("INTERMEDIATE", "Intermediate"),
                    ("ADVANCED", "Advanced"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Verified Entry"),
        ),
        migrations.AddField(
            model_name="dictionaryentry",
            name="source",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Source of Entry"
            ),
        ),
        migrations.AddField(
            model_name="stagingdictionaryentry",
            name="source",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Source of Entry"
            ),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="example_sentence_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Example Sentence in English"
            ),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="example_sentence_kh",
            field=models.TextField(
                blank=True, null=True, verbose_name="Example Sentence in Khmer"
            ),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="pronunciation_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="English Pronunciation",
            ),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="pronunciation_kh",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Khmer Pronunciation",
            ),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="word_en",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, "English word cannot be empty"
                    )
                ],
                verbose_name="English Word",
            ),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="word_en_definition",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "Definition must be at least 5 characters"
                    )
                ],
                verbose_name="English Word Definition",
            ),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="word_kh",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, "Khmer word cannot be empty"
                    )
                ],
                verbose_name="Khmer Word",
            ),
        ),
        migrations.AlterField(
            model_name="dictionaryentry",
            name="word_kh_definition",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "Definition must be at least 5 characters"
                    )
                ],
                verbose_name="Khmer Word Definition",
            ),
        ),
        migrations.AlterField(
            model_name="stagingdictionaryentry",
            name="example_sentence_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Example Sentence in English"
            ),
        ),
        migrations.AlterField(
            model_name="stagingdictionaryentry",
            name="example_sentence_kh",
            field=models.TextField(
                blank=True, null=True, verbose_name="Example Sentence in Khmer"
            ),
        ),
        migrations.AlterField(
            model_name="stagingdictionaryentry",
            name="pronunciation_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="English Pronunciation",
            ),
        ),
        migrations.AlterField(
            model_name="stagingdictionaryentry",
            name="pronunciation_kh",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Khmer Pronunciation",
            ),
        ),
        migrations.AlterField(
            model_name="stagingdictionaryentry",
            name="rejection_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reason for Rejection"
            ),
        ),
        migrations.AlterField(
            model_name="stagingdictionaryentry",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_staging_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stagingdictionaryentry",
            name="word_en",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, "English word cannot be empty"
                    )
                ],
                verbose_name="English Word",
            ),
        ),
        migrations.AlterField(
            model_name="stagingdictionaryentry",
            name="word_en_definition",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "Definition must be at least 5 characters"
                    )
                ],
                verbose_name="English Word Definition",
            ),
        ),
        migrations.AlterField(
            model_name="stagingdictionaryentry",
            name="word_kh",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, "Khmer word cannot be empty"
                    )
                ],
                verbose_name="Khmer Word",
            ),
        ),
        migrations.AlterField(
            model_name="stagingdictionaryentry",
            name="word_kh_definition",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "Definition must be at least 5 characters"
                    )
                ],
                verbose_name="Khmer Word Definition",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dictionaryentry",
            unique_together={("word_kh", "word_en")},
        ),
    ]
