# Generated by Django 5.1.7 on 2025-03-27 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0005_alter_stagingdictionaryentry_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("access_count", models.PositiveIntegerField(default=0)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="dictionary.dictionaryentry",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["device_id", "created_at"],
                        name="dictionary__device__588af4_idx",
                    ),
                    models.Index(
                        fields=["last_accessed"], name="dictionary__last_ac_faa94b_idx"
                    ),
                    models.Index(
                        fields=["access_count"], name="dictionary__access__9ddf1a_idx"
                    ),
                ],
                "unique_together": {("device_id", "word")},
            },
        ),
    ]
