# Generated by Django 5.1.7 on 2025-03-27 16:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0006_bookmark"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StagingEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word_kh",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, "Khmer word cannot be empty"
                            )
                        ],
                        verbose_name="Khmer Word",
                    ),
                ),
                (
                    "word_en",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, "English word cannot be empty"
                            )
                        ],
                        verbose_name="English Word",
                    ),
                ),
                (
                    "word_kh_type",
                    models.CharField(
                        choices=[
                            ("នាម", "Noun"),
                            ("កិរិយាសព្ទ", "Verb"),
                            ("គុណនាម", "Adjective"),
                            ("គុណកិរិយា", "Adverb"),
                            ("សព្វនាម", "Pronoun"),
                            ("ធ្នាក់", "Preposition"),
                            ("ឈ្នាប់", "Conjunction"),
                            ("ឧទានសព្ទ", "Interjection"),
                        ],
                        max_length=50,
                        verbose_name="Khmer Word Type",
                    ),
                ),
                (
                    "word_en_type",
                    models.CharField(
                        choices=[
                            ("NOUN", "Noun"),
                            ("VERB", "Verb"),
                            ("ADJECTIVE", "Adjective"),
                            ("ADVERB", "Adverb"),
                            ("PRONOUN", "Pronoun"),
                            ("PREPOSITION", "Preposition"),
                            ("CONJUNCTION", "Conjunction"),
                            ("INTERJECTION", "Interjection"),
                        ],
                        max_length=20,
                        verbose_name="English Word Type",
                    ),
                ),
                (
                    "word_kh_definition",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                5, "Definition must be at least 5 characters"
                            )
                        ],
                        verbose_name="Khmer Word Definition",
                    ),
                ),
                (
                    "word_en_definition",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                5, "Definition must be at least 5 characters"
                            )
                        ],
                        verbose_name="English Word Definition",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pronunciation_kh",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Khmer Pronunciation",
                    ),
                ),
                (
                    "pronunciation_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="English Pronunciation",
                    ),
                ),
                (
                    "example_sentence_kh",
                    models.TextField(
                        blank=True, null=True, verbose_name="Example Sentence in Khmer"
                    ),
                ),
                (
                    "example_sentence_en",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Example Sentence in English",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staging_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_staging_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staging Dictionary Entries",
                "ordering": ["-created_at"],
                "unique_together": {("word_kh", "word_en")},
            },
        ),
        migrations.DeleteModel(
            name="StagingDictionaryEntry",
        ),
    ]
