# Generated by Django 5.1.7 on 2025-03-28 03:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0007_stagingentry_delete_stagingdictionaryentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DictionaryEntry",
            new_name="Dictionary",
        ),
        migrations.RenameModel(
            old_name="StagingEntry",
            new_name="Staging",
        ),
        migrations.AddIndex(
            model_name="dictionary",
            index=models.Index(
                fields=["created_at", "index"], name="dictionary__created_d88f8f_idx"
            ),
        ),
    ]
